### ISSUE TITLE
Advanced Sign does not support credit card buys correctly

### ISSUE THREAD

**Issue by Cobra1117** [notabadminer/UniversalCoinsMod#26] opened 2015-10-09 14:54 UTC
If you set up a vending block to purchase an item, and you add a credit card to provide coins, the advanced block will display the "out of coins" message every time you access the vending block. (Unless you edit/save the price every time you open the GUI.)

**Comment by Cobra1117** [comment] 2015-10-09 15:14
Tested with 1.7.10-1.6.35

**Comment by notabadminer** [comment] 2015-10-09 16:35
Thanks for submitting these bugs. I will try to get fixes out soon. It
might be a couple days though.

Tested with 1.7.10-1.6.35

—
Reply to this email directly or view it on GitHub
<https://github.com/notabadminer/UniversalCoinsMod/issues/26#issuecomment-146899743>
.

**Comment by Cobra1117** [comment] 2015-10-09 18:30
No biggie. Sorry to dump so many at once--I've known about most of them for
a while, but haven't had time to properly test them and make sure they're
repeatable.

**Comment by notabadminer** [comment] 2015-10-11 01:33
I think the issue is resolved with the changes I've made. If it continues to  be a problem in the next update, reopen this issue.

**Closed by notabadminer** 2015-10-11 01:33 UTC

**Comment by Cobra1117** [comment] 2015-10-13 03:23
It's _mostly_ fixed. There's still a minor bug:
* Place an advanced sign
* Set up a vending block to buy items
* Add a credit card
* Close the GUI
* Open the GUI
* Close the GUI
* The sign now reads "Out Of Coins!"

(In other words, opening the GUI and not changing anything causes it to think it's out of coins)
