### ISSUE TITLE
Server crash loop when ender card left in trade station (player disconnected too)

### ISSUE THREAD

**Issue by ArmandVestibule** [notabadminer/UniversalCoinsMod#16] opened 2015-07-17 19:40 UTC
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/17/15 8:48 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at universalcoins.tile.TileTradeStation.getAccountBalance(TileTradeStation.java:587)
	at universalcoins.tile.TileTradeStation.activateBuySellButtons(TileTradeStation.java:95)
	at universalcoins.tile.TileTradeStation.func_145845_h(TileTradeStation.java:59)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at universalcoins.tile.TileTradeStation.getAccountBalance(TileTradeStation.java:587)
	at universalcoins.tile.TileTradeStation.activateBuySellButtons(TileTradeStation.java:95)
	at universalcoins.tile.TileTradeStation.func_145845_h(TileTradeStation.java:59)

-- Block entity being ticked --
Details:
	Name: TileTradeStation // universalcoins.tile.TileTradeStation
	Block type: ID #1695 (tile.blockTradeStation // universalcoins.blocks.BlockTradeStation)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-34,189,-18), Chunk: (at 14,11,14 in -3,-2; contains blocks -48,0,-32 to -33,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #1695 (tile.blockTradeStation // universalcoins.blocks.BlockTradeStation)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['cuboner'/434184, l='world', x=-31.02, y=188.00, z=-18.39]]
	Chunk stats: ServerChunkCache: 523 Drop: 0
	Level seed: 5574457897082764526
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4260872 game time, 4513298 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 59496 (now: false), thunder time: 12825 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1277196976 bytes (1218 MB) / 4018667520 bytes (3832 MB) up to 7478968320 bytes (7132 MB)
	JVM Flags: 1 total; -Xmx8024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 40993, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (ForgeMod.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (ForgeMod.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJAAAA	AppleMilkCore{1.0.3} [AppleMilkCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{IvToolkit} [1.2] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4(1).jar) 
	UCHIJAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJAAAA	securitycraft{v1.7.4.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.7.4.1.jar) 
	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAA	DCsAppleMilk{1.7.10_2.7c} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.7c.jar) 
	UCHIJAAAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.7c.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) 
	UCHIJAAAA	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.1} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.1.jar) 
	UCHIJAAAA	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHIJAAAA	BinnieCore{2.0-pre12} [Binnie Core] (binnie-mods-2.0-pre12.jar) 
	UCHIJAAAA	Botany{2.0-pre12} [Botany] (binnie-mods-2.0-pre12.jar) 
	UCHIJAAAA	ExtraBees{2.0-pre12} [Extra Bees] (binnie-mods-2.0-pre12.jar) 
	UCHIJAAAA	ExtraTrees{2.0-pre12} [Extra Trees] (binnie-mods-2.0-pre12.jar) 
	UCHIJAAAA	Genetics{2.0-pre12} [Genetics] (binnie-mods-2.0-pre12.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) 
	UCHIJAAAA	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) 
	UCHIJAAAA	farseek{1.0.8} [Farseek] (Farseek-1.0.8.jar) 
	UCHIJAAAA	ForgeEssentials{1.4.0} [Forge Essentials] (forgeessentials-1.7.10-1.4.0-server.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.344.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.344.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.11.4} [MalisisCore] (malisiscore-1.7.10-0.11.4.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.6} [Malisis' Doors] (malisisdoors-1.7.10-1.6.jar) 
	UCHIJAAAA	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (mam-1.7.10-1.0.2.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Mekanism{8.1.3} [Mekanism] (Mekanism-1.7.10-8.1.3.231.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.3} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.3.231.jar) 
	UCHIJAAAA	MekanismTools{8.1.3} [MekanismTools] (MekanismTools-1.7.10-8.1.3.231.jar) 
	UCHIJAAAA	NEIAddons{1.12.8.30} [NEI Addons] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.8.30} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.8.30} [NEI Addons: Botany] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.8.30} [NEI Addons: Forestry] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.8.30} [NEI Addons: Crafting Tables] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.8.30} [NEI Addons: Ex Nihilo] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
	UCHIJAAAA	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) 
	UCHIJAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAA	origin{3.5.1} [Origin] (Origin-1.7.10-3.5.1.jar) 
	UCHIJAAAA	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.27} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.27-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre5.89} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre5.89-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre5.89} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre5.89-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre5.89} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre5.89-Mechanical.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre5.89} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre5.89-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre5.89} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre5.89-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre5.89} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre5.89-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre5.89} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre5.89-Mechanical.jar) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAA	reccomplex{0.9.6.3} [Recurrent Complex] (RecurrentComplex-0.9.6.3.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCHIJAAAA	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.5.6} [Storage Drawers] (StorageDrawers-1.7.10-1.5.6.jar) 
	UCHIJAAAA	streams{0.1.4} [Streams] (Streams-0.1.4.jar) 
	UCHIJAAAA	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) 
	UCHIJAAAA	universalcoins{1.7.10-1.6.28} [Universal Coins] (UniversalCoins-1.7.10-1.6.28.jar) 
	UCHIJAAAA	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) 
	UCHIJAAAA	weather2{v2.3.9} [Localized Weather & Storms] (weather2-2.3.9 for MC v1.7.10.jar) 
	UCHIJAAAA	weepingangels{3.3.2} [Weeping Angels] (WeepingAngels-1.7.10-3.3.2.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.3} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	ForgeEssentials: Running ForgeEssentials 1.4.0 #785 (ab44004). Modules loaded: AuthLogin, Backups, Chat, Commands, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Tickets, WorldBorder, perftools
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 10; [GCEntityPlayerMP['cuboner'/434184, l='world', x=-31.02, y=188.00, z=-18.39]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ArmandVestibule** [comment] 2015-07-17 19:46
Once this error starts, the server crashes on boot with the same error indefinitely.  Disabling the mod to remove the affected blocks and items and then reloading with the mod reinstalled is a likely workaround.

**Comment by notabadminer** [comment] 2015-07-18 03:17
The issue is caused by an unactivated ender card being inserted into the trade station. The recipe for the ender card was not copying the nbt from the old card to the new one. I fixed the recipe and added checks to prevent this from happening. These changes will be in the next release and will work to fix a "corrupt" world if you have backups and wish to restore.

**Comment by ArmandVestibule** [comment] 2015-07-18 04:17
I found that the world survived after having deactivated the mod, loading the world, and then reactivating the mod afterward.  Effectively a reinstall.  Worked great.

Thanks for your efforts!

**Comment by notabadminer** [comment] 2015-07-23 03:19
This will be fixed with the next release. closing.

**Closed by notabadminer** 2015-07-23 03:19 UTC
